language: java
sudo: false
dist: trusty
script: 
  - mvn -Psafer -Pintegration -B -e -T 1C verify
jdk:
  - oraclejdk8

env:
# the SONAR_TOKEN variable
  - secure: "nrvHV6/M8crm+49iAq5QhI8JwhntRtB1HkdRDhzsNzCfslnrlxHitxB//z/hKd+f0fEK5raJdEapyzp9wZYrqSMBvCnQaJbtAph5CW089+JjTphOBezlHlLD0KlNkp+OmTjlu5Sb6z2VqcDAWWTCM+BqhiD4X+jgRy7ZwwbYW9Fi8rUufdDSeDGbofeoKwXLnzO53ZmpHMCRZLOMWaVVUGCIjSkIURY1JgHQU+3qJqNTYx5gxIdYb/cOQeY2EKw2fIkeEyrnnYHVyDqUAC/t0LpjUPfbNcRsz/io8nxw+XYQ0n5ogmfy3I5sWDf92J4+q/MYBYgZt9S7+mePIZMkSxFgrXhnHxb3Njb7Z69xWdipQcfDpAxB9MStDuHi2hLzHjblCCdRCOtLqXsPoNmAQCOi2NZH51BZzTtGJOSTQkAk1wG3NmzYNoII8aUcqZ/U6ZgOiw9fDf0ngXAfNOHXVqVtnNIyEmsLXLFTw3TxTsejacvo1gaBiCjjhOjoGqDjAa9stJLWZZWlE9Bvr4ohl28DEI7RsRjy5lX/k4vvg7yEdxh9RDlRN6AFWPnBQ5n37UFKoEg1Np5x8ghu7kAMVBgn7ezWTpQkXCD0c8vXl61AbiZxAJ7iizz0v5OV3t8pXhqQhM+3mdQTsjQv41gwcVke+6A1iF7Y2E6W6T78lsA="

addons:
  - apt:
    packages:
        - oracle-java8-installer
  - sonarqube: true

before_script:
- export GIT_BRANCH=$TRAVIS_BRANCH

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'

before_cache:
  # remove all the artifacts (JAR, ZIP) that are installed in local repo because of a previous installation
  - rm -rf $HOME/.m2/repository/com/eightkdata/mongowp
  - rm -rf $HOME/.m2/repository/com/8kdata/mongowp

install:
- mvn dependency:go-offline
  
after_success:
  - echo $TRAVIS_REPO_SLUG
  - if [[ $TRAVIS_REPO_SLUG = gortiz/mongowp ]]; then bash <(curl -s https://codecov.io/bash) || echo 'Codecov did not collect coverage reports'; else echo 'Codecov not notified'; fi
  - if [[ $TRAVIS_REPO_SLUG = gortiz/mongowp ]]; then mvn sonar:sonar || echo 'Error while notifying SonarQube'; else echo 'SonarQube not notified'; fi

before_deploy:
  - echo "<settings><servers><server><id>ossrh-snapshot</id><username>\${env.MAVEN_DEPLOY_USER}</username><password>\${env.MAVEN_DEPLOY_PASS}</password></server><server><id>ossrh-release</id><username>\${env.MAVEN_DEPLOY_USER}</username><password>\${env.MAVEN_DEPLOY_PASS}</password></server></servers></settings>" > ~/settings.xml

deploy:
- provider: script
  script: mvn -B -e -T 1C -Pdeploy -DskipTests=true deploy --settings ~/settings.xml
  skip_cleanup: true
  on:
    repo: 8kdata/mongowp
    branch: devel
    jdk: oraclejdk8